### PR TITLE
Update adyen.md

### PR DESCRIPTION
**Pull request by pranayaryal**
The author of the quote should be Raman Gupta. They seem to be present in `adyen.md` as well as `adobe.md`

### CODE REVIEW

**Comment by potiuk** [comment]
I guess @Jorricks  added it so he knows well who should be the author :) ? @Jorricks ?

**Comment by Jorricks** [comment]
Hey hey :)
The author of adyen.md is Me (Jorrick Sleijster). I guess I forgot to remove something what lead to this PR or? I'm not fully following what's happening here

**Comment by Jorricks** [comment]
I see now.
I forgot to update the quote to the following.
```
Apache Airflow helped us scale from 10 to 100+ users across 20+ teams with a variety of use cases. By writing our own plugins and creating custom user roles, we off-loaded our infrastructure team and gave power back to the airflow users.
```
I'll create another PR to fix it asap.

**Comment by Jorricks** [comment]
I think we can close this PR and continue with this PR: https://github.com/apache/airflow-site/pull/528

**Pull request closed without merging**
