### PR TITLE
All changes for Airflow 2.0

### PR DESCRIPTION
**Pull request by mik-laj**
Hello.

This PR contains changes that we should merge with the release of Airflow 2.0. It's based on `apache/airflow-2-0-docs`, so anyone can add more changes, but it's still a good idea to have PRs that target this branch.

I create this PR to have a better insight into changes. 

Related: https://github.com/apache/airflow-site/issues/314

Best regards,
Kamil Breguła

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
What are docs/list.html and docs/single.html templates used for?

**Comment by ashb** [comment]
@mik-laj Seeing something odd after running `site.sh build-site` when I visit `/docs/`

image

**Comment by ashb** [comment]
Oh I see what's happened

**Comment by mik-laj** [comment]
> What are docs/list.html and docs/single.html templates used for?

I don't know, but that's how other page were made. See: https://github.com/apache/airflow-site/tree/master/landing-pages/site/layouts/install

> @mik-laj Seeing something odd after running site.sh build-site when I visit /docs/

I'm starting to see it.

**Comment by mik-laj** [comment]
@ashb II don't have this problem.
Screenshot 2020-12-17 at 15 15 34
Can you try to to run ``rm -rf landing-pages/dist/;./site.sh build-site``?

**Comment by ashb** [comment]
That fixed it.

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
:tada:

**Pull request merged**
