### PR TITLE
Add Seniorlink to Use Cases

### PR DESCRIPTION
**Pull request by christopherpetrino**

### CODE REVIEW

**Comment by christopherpetrino** [comment]
@potiuk @kaxil @jhtimmins who are the appropriate people to tag on these types of PRs?

**Comment by potiuk** [comment]
I think blogs on airflow site are mostly for serious announcements and some big improvements from the community. We recently added an Airflow Medium publication and it's much better suited for publishing 'related' blogs

**Comment by potiuk** [comment]
Ah sorry , no - it is in use-case rather than blog. I think we have not discussed what can go here.

**Comment by potiuk** [comment]
I am not sure if we have any policy around that ? Do we want to have bigger number of small use cases or smaller number of bigger ones. I think we might want to discuss it at the devlist

**Comment by potiuk** [comment]
Let me start discussion

**Comment by potiuk** [comment]
I started discussion https://lists.apache.org/x/thread.html/rb567279f7ea1611ef2145c61c0c726bce540bbf06e21e0447bd7be6c@%3Cdev.airflow.apache.org%3E

**Comment by christopherpetrino** [comment]
Thanks, Jarek

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks! @christopherpetrino ! Cool case :). Cool company

**Comment by potiuk** [comment]
Hey @christopherpetrino  -> can you fix the logo? It's .svg instead of .png (missed that).

**Comment by christopherpetrino** [comment]
Thanks, Jarek! Tagging you in the new PR

**Pull request merged**
