### PR TITLE
Generate back-references to missing pages in providers

### PR DESCRIPTION
**Pull request by potiuk**

### CODE REVIEW

**Comment by potiuk** [comment]
This one provides redirects for old versions so that changing version in the menu for security/changelog and few other pages  does not cause "Not found" message.

**Comment by potiuk** [comment]
(Generated via #830 )

**Comment by potiuk** [comment]
cc: @amoghrajesh

**Comment by amoghrajesh** [comment]
Will review it in my IST hours tomorrow 👍

**Review by amoghrajesh — APPROVED** [review]
Looks awesome. Did not go through all the files, but generally looks good +1

**Pull request merged**
