### PR TITLE
Undockerize local & CI site builds

### PR DESCRIPTION
**Pull request by rossturk**
While I was working on #629, @potiuk recommended moving away from Docker for the functions of `site.sh`.

This updates the shell script to remove all of the Docker command execution, and makes changes throughout to remove hardcoded paths. It updates the GitHub workflow to install Hugo and Node, and it adds a few steps to the contributor docs to show users how to do the same.

As a side-effect, this makes `site.sh` and its related tools/processes work on ARM-based macOS machines.

### CODE REVIEW

**Comment by potiuk** [comment]
I think conflict needs resolving :)

**Comment by rossturk** [comment]
@potiuk ok! cleanup is done now, thanks for merging that other PR!

Fingers crossed. The GitHub workflow does different stuff on merge to main, hope there aren't surprises.

**Comment by potiuk** [comment]
> @potiuk ok! cleanup is done now, thanks for merging that other PR!
> 
> Fingers crossed. The GitHub workflow does different stuff on merge to main, hope there aren't surprises.

Will there be any surprises, we will fix them :)

**Comment by potiuk** [comment]
> > @potiuk ok! cleanup is done now, thanks for merging that other PR!
> > Fingers crossed. The GitHub workflow does different stuff on merge to main, hope there aren't surprises.
> 
> Will there be any surprises, we will fix them :)

BTW. The way I test merges to main (airlfow has VASTLY different workflow when merging) is `git push -f my_fork my_branch:main` -> this will push your branch as main (i..e. same as merge) and if you configure the same SECRETS that we have in "apache" in your fork + make sure that the "bucket" name is configurable from secret (I think it is) you can test merge workflow in your own fork with relative ease

**Comment by potiuk** [comment]
Merge running https://github.com/apache/airflow-site/actions/runs/2657942667 , let's see.

**Comment by potiuk** [comment]
All good. Build is Green, the website did not blow up :) :+1:

**Comment by Bowrna** [comment]
@rossturk I get an error saying `yarn` command not found in my local machine( m1 mac os). Am I missing executing any specific step in documentation?

**Comment by potiuk** [comment]
yep. You need yarn to be installed

**Pull request merged**
