### PR TITLE
add geniumcloud in ecosystem

### PR DESCRIPTION
**Pull request by sumyan**
Please review an additions to the list of tools based on Airflow.

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Comment by XD-DENG** [comment]
This product didn't mention Airflow (implicitly or explicitly) at all in the site. I'm not sure if it's valid to be added here.

**Review by XD-DENG — DISMISSED** [review]
As mentioned in the comment above

**Comment by sumyan** [comment]
Updated the page, please review.

**Comment by sumyan** [comment]
> Updated the page, please review.

**Comment by sumyan** [comment]
> This product didn't mention Airflow (implicitly or explicitly) at all in the site. I'm not sure if it's valid to be added here.

I assure you the product has direct relation to the Airflow, since it's built on top of it. There is no point of adding to the list if it is not related. Please re-check the page again.

**Pull request merged**
