### PR TITLE
Add documentation for packages - 2023-05-17

### PR DESCRIPTION
**Pull request by eladkal**
cc @potiuk this one should be fine

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
What was the issue with the previous one ? How can we diagnose that ? (I tend to trust the generation process and approve as doc PRs are huge and almost impossible to review, are there some things that we should specifically look out for ?)

**Comment by potiuk** [comment]
> What was the issue with the previous one ? How can we diagnose that ? (I tend to trust the generation process and approve as doc PRs are huge and almost impossible to review, are there some things that we should specifically look out for ?)

This was "once a blue moon" case. It was really a result of improvement I added few weeks ago to improve the "min-airflow-version" automation (which happens every 12 months or so). 

I've modified the templates for index.rst  to include the information about "minimum required airflow version" in https://github.com/apache/airflow/pull/30994  (and added full automation for it) but the templated missed a single lin.,

This one fixes the template: https://github.com/apache/airflow/pull/31323  and follow up today that fixes the generated indexes https://github.com/apache/airflow/pull/31343.

I will add the description above to #31343 to the commit message in a moment.

**Comment by potiuk** [comment]
Now - this is finally fixed @eladkal 

image

**Comment by potiuk** [comment]
> are there some things that we should specifically look out for ?)

@pierrejeambrun  Well. That's difficult by looking at the code :). The last fixup I did (adding 74 empty lines to index.rst files) resulted in this fixup:

> add-documentation-2023-05-17(+15823/-14535)

Not for the faint of hearts to review that one.

In this case,  the problem we had was that when @eladkal looked at the generated docs (which is cool) he noticed this:

image

The `easy` way to check the PRs is to just look at teh docs generated. And that's actually easy. Check it out, get to one of the versions just generated and start python server:

```
⌁0% [jarek:~/code/airflow-site/docs-archive/apache-airflow-providers-airbyte/3.3.0] [airflow-3.9] add-documentation-2023-05-17 1 ± python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

Then you will be able to look at these particular provider's docs generated

**Comment by eladkal** [comment]
Release is cancelled. will open new PR for RC2

**Pull request closed without merging**
