### PR TITLE
Added integration-logos and updated integrations.json

### PR DESCRIPTION
**Pull request by rozza**

### CODE REVIEW

**Comment by rozza** [comment]
Refs: https://github.com/apache/airflow/issues/23748

Updated the integrations.json file by running [generate-integrations-json.py(https://github.com/apache/airflow/blob/main/scripts/tools/generate-integrations-json.py)

**Comment by potiuk** [comment]
@mik-laj  - is this fine that this many new images are generated ? It looks a bit strange?

**Comment by rozza** [comment]
> @mik-laj - is this fine that this many new images are generated ? It looks a bit strange?

It surprised me also - feel free to run the generate-integrations-json.py to verify. I think it might not have been 
run after https://github.com/apache/airflow/pull/13717 added in all the new logos.

**Comment by potiuk** [comment]
Actually there is a problem that you need to solve with installing and running pre-commit (it will lint and re-format .json properly for you once you run it on the last commit).

**Comment by rozza** [comment]
Run the pre commit hook - json file now linted / reformat.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
