### PR TITLE
Add Airflow Survey 2023 results page

### PR DESCRIPTION
**Pull request by merobi-hub**
This adds a new page with visualizations of the results and a link to the raw data.

screencapture-0-0-0-0-3000-survey-2024-01-03-20_29_22

### CODE REVIEW

**Comment by potiuk** [comment]
Oh .... wooooooowowowooow

**Comment by potiuk** [comment]
AAAAND .... ready ! https://airflow.apache.org/survey/

**Comment by kaxil** [comment]
Great work @merobi-hub

**Comment by o-nikolas** [comment]
This is so awesome!!! Great work :+1: :rocket:

**Pull request merged**
