### PR TITLE
(#685) feat: docker compose v2

### PR DESCRIPTION
**Pull request by seunggabi**
- #685 
- ide fix space & eof newline
- can I rollback ?

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Yeah. We can fix it everywhere now. Sufficient time passed for people to start using `docker compose`. I just wonder @seunggabi  - do you know how `dockoer compose` works with other tools such as colima using docker runtime ?

**Comment by potiuk** [comment]
> @potiuk [docker/compose#9598 (comment)](https://github.com/docker/compose/pull/9598#issuecomment-1167305603)
> 
> yes. As far as I know, it guarantees backward compatibility.

Including colima?

**Comment by seunggabi** [comment]
@potiuk 
let me check.
I think that, v2 is okay.

but, cross check by docker forums.
https://forums.docker.com/t/docker-compose-docker-compose-v2-support-colima-guarantees-backward-compatibility/131967

please wait for answer.
thx.

**Comment by seunggabi** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#initialize-the-database

actually, now docs mixed v1 & v2 haha.


스크린샷 2022-11-23 오후 9 21 28

**Comment by seunggabi** [comment]
@potiuk 

### summary
```
v2 is designed to be backward compatible in theory
I understood that we couldn’t guarantee 100% because we didn’t test everything on a 1:1 basis.
```
https://forums.docker.com/t/docker-compose-docker-compose-v2-support-colima-guarantees-backward-compatibility/131967/2

### docker forums leader said..
```
I am not sure what you need an answer to. If you want more people to read your question and try to answer, it is better to descibe the issue directly in the post instead of linkin an other forum so we can read everything, find out what the problem is, which was the question and then answer here…

Despite that I have read the issue on GitHub and I am still not sure what the question is. Is it that you would like to know if Docker Compose v1 is compatible with v2 so you can start to use docker compose command in airflow instead of docker-compose.

In theory, yes. On the other hand Docker Compose v2 had a bug from the beginning, because parsing of environment variables in the compose file had changed so previously working compose files would not always work with Compose v2. I submitted a pull request to fix it and it was eventually accepted, but I haven’t tried if that change was implemented in a Docker Compose release.

The othe rproblem could be that Docker Compose v1 supported different compose yaml versions, but there is no version attribute in a Compose V2 file so some features may work differently if the application relied on something that was or wasn’t in a specific compose yaml version…

This is just an example so I think in most of the cases you would not have problem with Compose v2, but it is not impossible. I wouldn’t rely on an intended compatibility in any application so I wouldn’t do that with Docker Compose either. If you want to make sure that everything works, you need to test every command.

The library in Docker Compose v2 didn’t have a test for multiple variables in one string and this is why the developers didn’t notice this issue,
```

image

**Comment by rimelek** [comment]
I added some new notes to be more precise on the Docker forum in the topic that @seunggabi linked. So most of the compose files would work with Docker Compose v2, but not all of them. You can use the `--compatibility` flag, but I haven't tested how it works. Although all of my old compose files worked even without compatibility mode. Don't forget to check the docs about the compatibility of v1 and v2:

https://docs.docker.com/compose/cli-command-compatibility/

**Comment by potiuk** [comment]
Let's see :)

**Pull request merged**
