### PR TITLE
Announce Apache Airflow 2.3.1

### PR DESCRIPTION
**Pull request by ephraimbuddy**

### CODE REVIEW

**Comment by potiuk** [comment]
I think we need a bit different format (see the  lst release)

**Comment by potiuk** [comment]
Otherwise it ends up as single line :)

**Comment by ephraimbuddy** [comment]
Yeah. Have fixed it

**Comment by ephraimbuddy** [comment]
cc: @potiuk

**Review by potiuk — APPROVED** [review]

**Pull request merged**
