### PR TITLE
Update integrations.json

### PR DESCRIPTION
**Pull request by ecerulm**
The `integrations.json` generated with:

    cd airflow
    AIRFLOW_SITE_DIRECTORY=/Users/ecerulm/git/airflow-site/ python scripts/tools/generate-integrations-json.py

@mik-laj

### CODE REVIEW

**Comment by mik-laj** [comment]
I changed the base branch from master to airflow-2-0-docs. Can you do a rebase?

**Comment by ecerulm** [comment]
yes, I forgot about that

**Comment by ecerulm** [comment]
rebased and sorted by lowercase name

**Comment by mik-laj** [comment]
CI was sad, so I made some changes.

**Comment by mik-laj** [comment]
Thanks for working on this. It is important for users to know what integrations we have, as this is a big advantage of Airflow. 2.0.  The Airflow 1.10 had much less integration and their documentation had a lot of gaps. The documentation for Airflow 2.0 integration is a big step forward.

**Pull request merged**
