### PR TITLE
Publish new website - AIP-11

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,

The site has been accepted by the community on the mailing listThe site has been accepted by the community on the mailing list

https://lists.apache.org/thread.html/05820dfb65ac0d514e34720d3fea130744f999196273b3a51955e843@%3Cdev.airflow.apache.org%3E
the voting results:
9 binding +1s
2 non-binding +1s

There were no -1 nor 0 votes. 

I have prepared this PR with a new website and i want to officially  publish.
 
Thanks!

### CODE REVIEW

**Comment by ashb** [comment]
Have the URLs for docs changed?

**Comment by mik-laj** [comment]
Yes. All documents have new links. In most cases
http://airflow.apache.org/index.html => http://airflow.apache.org/docs/stable/index.html

**Comment by ashb** [comment]
If they have I'd like us to have a .htaccess set up to redirect old links:

`$ver/*` -> `docs/$ver/*` for the "permalink"/versioned ones should be easy.

Having a link for all the "current" ones i.e. `concepts.html` to `docs/concepts.html` could be done with an script to build the redirect rules?

**Comment by mik-laj** [comment]
Do we have support for .htaccess?

**Comment by ashb** [comment]
Let me check in asf-slack

**Comment by ashb** [comment]
https://www.apache.org/dev/project-site.html#configure yes but:

> Yes, the central config file allows you to use .htaccess files in your website directories to control configuration. Of course, reading and parsing an .htaccess file on each request can slow down the server, so you should consider requesting an adjustment in the central config file for permanent configuration changes.

**Comment by mik-laj** [comment]
Will it be alright for you if I did it later? Now, this requires more thought, because we have a very complex directory structure. I will try to take care of it tomorrow. I am mainly worried about subdirectories so that they also work properly.  We don't have a transition environment configured yet, so I will have to set up the whole environment locally.  I am not sure which means that there is limited support for .htacccess  Do we have mod_rewrite?

**Comment by ashb** [comment]
Yes we have mod_rewrite enabled - for example https://git-wip-us.apache.org/repos/asf?p=incubator.git;a=blob;f=assets/.htaccess;h=c1c53fe407a149c52ed853ca45dc806d36858fb1;hb=HEAD

I'd really like this to be done before we merge this PR to -  I'm a very strong believer that we shouldn't have URLs suddenly 404 -- it gives a bad experience to users (and I think impacts search results from Google etc.)

**Comment by kgabryje** [comment]
Hi @ashb! I set up the redirects that you requested. Can you please take a look?
https://github.com/apache/airflow-site/blob/00ed176e068742100c54ebcd143eb472459486af/.htaccess

**Comment by ashb** [comment]
@kgabryje Amazing! I think the one thing that is missing is objects.inv.

**Comment by mik-laj** [comment]
@kgabryje  Kamil has already gone home.
I added this file.
https://github.com/apache/airflow-site/pull/198/commits/fa7badd99962f8db8eec4c18e20f2c0f14453ddc

**Comment by kgabryje** [comment]
Thanks Kamil!

**Comment by kaxil** [comment]
LGTM but I will wait for @ashb to confirm !

**Comment by ashb** [comment]
💥

**Comment by kaxil** [comment]
Wohoooo 🎉

**Pull request merged**
