### PR TITLE
Add docs for July 2021 providers.

### PR DESCRIPTION
**Pull request by potiuk**

### CODE REVIEW

**Review by kaxil — APPROVED** [review]
lol -- 1million changes -- nice. Will complete the review in 10 years :D

**Comment by potiuk** [comment]
You can do it @kaxil ! don't give up!

**Comment by potiuk** [comment]
With doc-only changes for all other providers we are at 1.5 M now @kaxil :)

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
haha .. Give me another 2 years please

**Pull request merged**
