### PR TITLE
Adding season of docs experience to the blog

### PR DESCRIPTION
**Pull request by KKcorps**

### CODE REVIEW

**Comment by KKcorps** [comment]
@aijamalnk  Can you review this?

**Comment by mik-laj** [comment]
@KKcorps Travis is sad. Can you fix it?
```
pre-commit run --all-files && git add .&& git commit --fixup HEAD
```

**Comment by aijamalnk** [comment]
Hi, 

Sorry, I am going on vacation for 2 weeks, and I will be able to review this when i am back on Jan 10.

**Comment by aijamalnk** [comment]
this lgtm. Is there any way to look at the staged post @mik-laj ? Also feel free to merge if it is good to you. 

Thank you!

**Comment by mik-laj** [comment]
@aijamalnk Does this site comply with our guidelines?.
Guidelines: https://lists.apache.org/thread.html/ef2ce0279ca7532d0206ca77b121bdf28120801e352c1113a0cf6167%40%3Cdev.airflow.apache.org%3E
Similar article: https://www.kharekartik.dev/2019/12/14/experience-in-gsod-2019/

**Comment by KKcorps** [comment]
hi @mik-laj , although I have published it to my personal blog, I haven't provided any link to that here to drive away the traffic. Also, the content here is complete.

**Pull request merged**
