### PR TITLE
Add gopidesupavan/tirkarthi/dirrao to airflow site

### PR DESCRIPTION
**Pull request by gopidesupavan**

### CODE REVIEW

**Comment by tirkarthi** [comment]
Thanks @gopidesupavan for the PR. If you are okay can you please also update the PR with below info for my account to keep it as a single PR?

```
  {
    "name": "Karthikeyan Singaravelan",
    "github": "https://github.com/tirkarthi",
    "image": "https://github.com/tirkarthi.png",
    "nick": "tirkarthi"
  },
```

cc: @dirrao as this is one of the steps in new committer onboarding https://github.com/apache/airflow/blob/main/COMMITTERS.rst#new-committer-onboarding-steps

**Comment by tirkarthi** [comment]
Created a PR to the your fork https://github.com/gopidesupavan/airflow-site/pull/1 . Please review and merge. Thanks.

**Comment by gopidesupavan** [comment]
> Created a PR to the your fork [gopidesupavan#1](https://github.com/gopidesupavan/airflow-site/pull/1) . Please review and merge. Thanks.

cool 😄

**Comment by gopidesupavan** [comment]
@dirrao please let me know i will include your details?

**Comment by dirrao** [comment]
@gopidesupavan 
Can you please update my details as follows?
  {
    "name": "Gopal Dirisala",
    "github": "https://github.com/dirrao",
    "image": "https://github.com/dirrao.png",
    "nick": "dirrao"
  },

**Comment by gopidesupavan** [comment]
> @gopidesupavan Can you please update my details as follows? { "name": "Gopal Dirisala", "github": "https://github.com/dirrao", "image": "https://github.com/dirrao.png", "nick": "dirrao" },

Done :)

**Review by tirkarthi — COMMENTED** [review]
LGTM. Thanks @gopidesupavan .

**Review by potiuk — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
