### PR TITLE
Publish .asf.yaml on asf-site branch

### PR DESCRIPTION
**Pull request by mik-laj**
Hello

ASF Publishing tools can't detect his file.  According to [asf infra report](https://infra-reports.apache.org/site-source/), we must have this file on the `asf-site` branch.

> This page will also tell you which  branch you are currently publishing as your web site. This is (should  be) the branch that you must add a .asf.yaml meta file to.

For more, see: https://lists.apache.org/thread.html/raf30ca1c77b81bc8c535c53b7aff38e1ff3c755ce84f4a40a6d8ad53%40%3Cusers.infra.apache.org%3E

Best regards,
Kamil Breguła

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by mik-laj** [comment]
This didn't help as our CI is pushing changes to the `gh-pages` branch. I changed it last week, because it is required by asf infra. 

> The ghp_branch setting can ONLY be either master or gh-pages.

https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-WebSiteDeploymentServiceforGitRepositories

For now, I have manually synced `gh-pages` branch to `asf -site` to research this process more. This may change the name of the branch that appears in the report and the file asf.yaml will be read from the new branch.

**Comment by ashb** [comment]
Do we use GitHub Pages?

**Comment by mik-laj** [comment]
> Do we use GitHub Pages?

I tried to turn it on but I'm not sure if it started working. See: https://github.com/apache/airflow-site/pull/430

**Comment by potiuk** [comment]
I just merged the provider changes and seems that the 'main` build get green but the doc page does not seem to refresh :( For example https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html should be 2.0  and https://airflow.apache.org/docs/ should contain "Asana" provider :(.

The commit is correctly displayed here: https://infra-reports.apache.org/site-source/ 😕 

Help ...

**Comment by kaxil** [comment]
I cherry-picked it to asf-site @potiuk -- The pages should now be updated

**Comment by kaxil** [comment]
@potiuk Asana is now in there: https://airflow.apache.org/docs/apache-airflow-providers-asana/stable/index.html

**Comment by mik-laj** [comment]
I created a INFRA ticket: https://issues.apache.org/jira/browse/INFRA-22028

**Comment by potiuk** [comment]
Airflow is Green now in *https://infra-reports.apache.org/site-source/, I guess we can close the JIRA :)

**Pull request merged**
