### PR TITLE
Add Airflow Summit CTA.

### PR DESCRIPTION
**Pull request by potiuk**

### CODE REVIEW

**Comment by potiuk** [comment]
image (10)

**Comment by potiuk** [comment]
Good enough :)

**Review by ryanahamilton — APPROVED** [review]

**Comment by potiuk** [comment]
@mik-laj - not sure - do we have to publish a theme after that ( I never know :) )

**Comment by kaxil** [comment]
> @mik-laj - not sure - do we have to publish a theme after that ( I never know :) )

If we want to release a new version of Airflow, providers or Helm Chart, then yes -- or else we will need to apply these changes manually. So not 100% needed per see if we want to find/replace manually as we will revert it after the Summit

**Comment by potiuk** [comment]
We want to submit providers docs now :) . So yeah

**Comment by potiuk** [comment]
Will do it then :)

**Pull request merged**
